name: 'Trigger Workflow and Wait for Completion'
description: Trigger a GitHub workflow and optionally wait for it to complete
author: "Or Moshe Bohadana"

inputs:
  workflow_file: 
    description: 'The workflow file'
    required: true
  inputs:
    required: false
    description: 'Send inputs to the workflow'
  repo:
    required: true
    description: 'Repo name'
  owner:
    required: true
    description: 'The owner of the repo'
  branch:
    required: true
    default: 'main'
    description: 'The branch that the workflow exists'
  token:
    required: true
    description: 'Token with permissions to trigger the workflow'
  wait_until:
    required: false
    description: 'Wait until the workflow is finished'
  correlation_id:
    required: false
    description: 'Correlation ID for tracking the workflow run'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/ormbo/trigger-workflow:latest'

  args:
    - ${{ inputs.workflow_file }}
    - ${{ inputs.inputs }}
    - ${{ inputs.repo }}
    - ${{ inputs.owner }}
    - ${{ inputs.branch }}
    - ${{ inputs.token }}
    - ${{ inputs.wait_until }}
    - ${{ inputs.correlation_id }}